using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClinicalManagementSystemNewRD.Model
{
    public class PatientToken
    {
        public int TokenID { get; set; } // Auto-generated Token ID
        public int PatientID { get; set; } // Foreign Key from Patient table
        public string TokenValue { get; set; } // Unique Token Value generated by a stored procedure
        public DateTime GeneratedDateTime { get; set; } // Timestamp when the token was generated

       
    }

}

